"""PlatformIO pre-build step.

1. Compresses the embedded web pages in src/webui.h into src/webui_gz.h.
   The dashboard is ~141 KB of HTML/CSS/JS and gzips to ~24 KB, which is
   ~130 KB of flash back for free. Browsers decompress it themselves.
   Keep editing src/webui.h; this regenerates the compressed copy on every build.

2. Stops TJpg_Decoder dragging in the whole SD/SdFat stack (~22 KB). Its
   bundled User_Config.h defines TJPGD_LOAD_SD_LIBRARY and this board has no
   SD card. The file lives in .pio/libdeps, so it is re-patched after every
   dependency install.
"""
import gzip
import os
import re

Import("env")  # noqa: F821  (injected by PlatformIO)

PAGE_RE = re.compile(r'const char (\w+)\[\] PROGMEM = R"rawliteral\((.*?)\)rawliteral";', re.S)


def gzip_web_pages(source="src/webui.h", target="src/webui_gz.h"):
    with open(source, encoding="utf-8") as handle:
        pages = PAGE_RE.findall(handle.read())
    if not pages:
        raise RuntimeError("no PROGMEM pages found in %s" % source)

    out = ["// GENERATED by tools/prebuild.py from %s - do not edit." % source,
           "#ifndef WEBUI_GZ_H", "#define WEBUI_GZ_H", "#include <Arduino.h>", ""]
    for name, body in pages:
        raw = body.encode("utf-8")
        blob = gzip.compress(raw, 9)
        rows = [", ".join("0x%02x" % b for b in blob[i:i + 16]) for i in range(0, len(blob), 16)]
        out.append("// %s: %d B raw -> %d B gzip" % (name, len(raw), len(blob)))
        out.append("const size_t %s_gz_len = %d;" % (name, len(blob)))
        out.append("const uint8_t %s_gz[] PROGMEM = {\n    %s\n};\n" % (name, ",\n    ".join(rows)))
        print("prebuild: %s %d B -> %d B gzip" % (name, len(raw), len(blob)))
    out += ["#endif", ""]
    text = "\n".join(out)

    # Only rewrite when the content changed, so we do not force a rebuild every time.
    if os.path.exists(target):
        with open(target, encoding="utf-8") as handle:
            if handle.read() == text:
                return
    with open(target, "w", encoding="utf-8") as handle:
        handle.write(text)


def drop_tjpg_sd_support():
    path = os.path.join(env.subst("$PROJECT_LIBDEPS_DIR"), env.subst("$PIOENV"),
                        "TJpg_Decoder", "src", "User_Config.h")
    if not os.path.exists(path):
        # Should not happen: `pio run` installs lib_deps before extra scripts run.
        # Warn loudly rather than silently shipping the ~22 KB SD stack.
        print("prebuild: WARNING %s not found, SD stack may still be linked "
              "(build again and it will be patched)" % path)
        return
    with open(path, encoding="utf-8") as handle:
        text = handle.read()
    patched = text.replace("\n#define TJPGD_LOAD_SD_LIBRARY",
                           "\n// #define TJPGD_LOAD_SD_LIBRARY  // disabled by tools/prebuild.py: no SD card on this board")
    if patched != text:
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(patched)
        print("prebuild: disabled TJPGD_LOAD_SD_LIBRARY in %s" % path)


gzip_web_pages()
drop_tjpg_sd_support()
